version: "3.11"

services:

  app-BOOT2:
    container_name: app-BOOT2
    build: ./app
    command: make up
    env_file:
      - 'app/.env'
    volumes:
      - ./app:/opt/app/app
    restart: always
    ports: 
      - "8001:8000"

networks:
  default_network: