version: "3"

services:
  app:
    build: ./app
    depends_on:
      - db
    restart: always
    ports: 
      - "8000:8000"
      
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example