version: "3.11"

services:

  app-boot2:
    container_name: app-boot2
    build: ./app
    command: make up
    depends_on:
      - db-boot2
    env_file:
      - 'app/.env'
    environment:
      - DOCKER=True
    volumes:
      - ./app:/opt/app/app
    restart: always
    ports: 
      - "8001:8000"

  db-boot2:
    container_name: db-boot2
    image: postgres:latest
    restart: always
    env_file:
      - 'app/.env'
    ports: 
      - "5433:5432"
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data

networks:
  default_network: