version: "3.11"

services:

  app:
    container_name: FastAPI
    build: ./app
    command: make up
    depends_on:
      - db
    env_file:
      - 'app/.env'
    environment:
      - DOCKER=True
    volumes:
      - ./app:/opt/app/app
    restart: always
    ports: 
      - "8000:8000"

  db:
    container_name: PostgreSQL
    image: postgres:latest
    restart: always
    env_file:
      - 'app/.env'
    ports: 
      - "5432:5432"
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data

networks:
  default_network: