version: "3.11"

services:

  app-boot2:
    container_name: app-boot2-BOOT2
    build: ./app
    command: make up
    depends_on:
      - db-boot2
    env_file:
      - 'app/.env-prod'
    volumes:
      - ./app:/opt/app/app
    restart: always
    ports: 
      - "8001:8000"

networks:
  default_network: