name: Run Test
on:
  push:
    branches:
      - dev
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.1
    - name: Install dependencies
      run: |
        make install
    - name: Test
      run: |
        make test
        
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.1
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Build
      run: |
        make build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy
      run: |
        echo Deploy...
