name: Run Test
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.1
    - name: Install dependencies
      run: |
        make install
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.1
    - name: Test
      run: |
        make test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Test
      run: |
        echo Deploy on server successfully completed!