name: Run Test
on:
  push:
    branches:
      - dev
      - main
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.1
    - name: Install dependencies
      run: |
        make install
    - name: Test
      run: |
        make test
        
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.1
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Build Docker Image
      run: cd app && docker build -t eugenestudio/boot2:latest .
    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && \
        echo "The logining has done successful"

    - name: Push Docker Image to Docker Hub
      run: docker push eugenestudio/blog:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy
      run: |
        echo Deploy...
